version: '3.3'
services:

  db:
    container_name: foodgram-postgres
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: foodgram-django
    image: frodo80/foodgram-backend:latest
    restart: always
    volumes:
      - static_dir:/app/foodgram/static/
      - media_dir:/app/foodgram/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: foodgram-react
    image: frodo80/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram-nginx
    image: nginx:1.23-alpine
    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/var/html/static/
      - media_dir:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  static_dir:
  media_dir:
  postgres_data:

