# Generated by Django 3.2 on 2023-06-19 13:40

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=None,
                force_format="JPEG",
                keep_meta=True,
                quality=-1,
                scale=None,
                size=(500, 500),
                upload_to="recipes/",
                verbose_name="Картинка",
            ),
        ),
    ]
